#! /usr/bin/python3

import cgi
import passwords
import MySQLdb
print("Content-Type: text/html")
print("Status: 200 OK")
print()

form = cgi.FieldStorage()

lineID = form.getvalue("lineID")
seats = form.getvalue("seats")

if lineID and seats:
    conn = MySQLdb.connect(host = passwords.SQL_HOST,
    user = passwords.SQL_USER,
    passwd = passwords.SQL_PASSWD,
    db = "my_database")
    cursor1 = conn.cursor()
    cursor1.execute("UPDATE cars SET seats=%s WHERE id=%s;" % (seats,lineID))
    cursor1.close()
    conn.commit()


print("""
<html>
<body>
<header>
        <title>sqlDynamicTable</title>
</header>

<center>
<table style="width:50%" cellpadding ="10" border = "1">
<caption><h2><b>Table: cars<b></h2></caption>
  <col width="150">
  <col width="150">
  <col width="150">
  <col width="150">
  <tr>
    <th>id</th>
    <th>Brand</th>
    <th>Model</th>
    <th>Seats</th>
  </tr>
""")

conn = MySQLdb.connect(host = passwords.SQL_HOST,
    user = passwords.SQL_USER,
    passwd = passwords.SQL_PASSWD,
    db = "my_database")
cursor2 = conn.cursor()
cursor2.execute("SELECT * FROM cars;")
results = cursor2.fetchall()
cursor2.close()
conn.close()

for line in results:
    print("""
    <tr>
    <td>{}</td>
    <td>{}</td>
    <td>{}</td>
    <td>{}</td>
    </tr>
    """.format(line[0],line[1],line[2],line[3]))
  
print("""
</center>        
</body>
</html>
""")


